tasks:
    - name: aws-cli
      env:
        AWS_CLI_AUTO_PROMPT=on-partial
      before:
        cd /workspace
        curl "https://awscli.amazonaws.com/AWSCLIV2.msi" -o "AWSCLIV2.msi"
        #sudo ./aws/install

# export AWS_ACCESS_KEY_ID=AKIA2MKR6HWFTEVSMENT
# export AWS_SECRET_ACCESS_KEY_ID=HOGq1S32e/HXPSy3LRcpTrpCb4PA28IE4stZP2Iv
# export AWS_DEFAUL_REGION=us-east-1