tasks:
    - name: aws-cli
      env:
        AWS_CLI_AUTO_PROMPT=on-partial
      before:
        cd /workspace
        curl "https://awscli.amazonaws.com/AWSCLIV2.msi" -o "AWSCLIV2.msi"
        #sudo ./aws/install